apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: coding-sap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: shubh301/app1:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: coding-sap
spec:
  type: NodePort
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000