apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: coding-sap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: shubh301/app2:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: coding-sap
spec:
  type: NodePort
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
